version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5000"
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    ports:
      - "5002:5000"
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "5003:5000"
    networks:
      - microservices-network
    depends_on:
      - user-service
      - product-service

networks:
  microservices-network:
    driver: bridge

