version: '3.8'
services:
  user-service:
    image: obaidullahofficial/shopEase:user_service
    networks:
      - microservices-network

  product-service:
    image: obaidullahofficial/shopEase:product_service
    networks:
      - microservices-network

  order-service:
    image: obaidullahofficial/shopEase:order_service
    networks:
      - microservices-network
    depends_on:
      - user-service
      - product-service

networks:
  microservices-network:
    driver: bridge
