# Specify the version of the Docker Compose file format
version: '3.8'

# Define the services (containers) that make up the application
services:
  
  # Configuration for the user service
  user-service:
    # Build the Docker image for the user service using the Dockerfile in the ./user-service directory
    build: ./user-service
    # Map port 5000 in the container to port 5001 on the host
    ports:
      - "5001:5000"
    # Connect the user service to the custom network for inter-service communication
    networks:
      - microservices-network

  # Configuration for the product service
  product-service:
    # Build the Docker image for the product service using the Dockerfile in the ./product-service directory
    build: ./product-service
    # Map port 5000 in the container to port 5002 on the host
    ports:
      - "5002:5000"
    # Connect the product service to the custom network for inter-service communication
    networks:
      - microservices-network

  # Configuration for the order service
  order-service:
    # Build the Docker image for the order service using the Dockerfile in the ./order-service directory
    build: ./order-service
    # Map port 5000 in the container to port 5003 on the host
    ports:
      - "5003:5000"
    # Connect the order service to the custom network for inter-service communication
    networks:
      - microservices-network
    # Ensure the order service starts only after the user and product services are up and running
    depends_on:
      - user-service
      - product-service

# Define a custom network to allow services to communicate with each other
networks:
  microservices-network:
    # Use the bridge driver for the custom network
    driver: bridge
